apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kryptokrona
  name: kryptokrona
  namespace: kryptokrona
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kryptokrona
  strategy: {}
  template:
    metadata:
      labels:
        app: kryptokrona
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kryptokrona
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: jrkalf/xmrig-kryptokrona:latest
          name: kryptokrona
          command: ["/xmrig/xmrig"]
          args: ["-c", "/xmrig/etc/config.json"]
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: config-volume
              mountPath: /xmrig/etc
      volumes:
        - name: config-volume
          configMap:
            name: kryptokrona-config
