name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_API }}
      -
        name: Hello World!
        run: echo "hello world!"
        if: github.event_name == 'pull_request'
        continue-on-error: true
#       -
#         name: Build and push Testing
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           platforms: linux/amd64,linux/arm64,linux/arm/v7
#           tags: jrkalf/xmrig-kryptokrona:testing-$(date +%s)
#         if: github.ref != 'refs/heads/main'
      -
        name: Build and push production
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: jrkalf/xmrig-kryptokrona:gha-$(date +%s)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

#         run: docker buildx build --platform linux/amd64 . --file Dockerfile --push --tag jrkalf/xmrig-kryptokrona:gha-testing-$(date +%s)
